name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: sudo apt-get install python3-pip
      - name: Install dependencies
        run: pip3 install -r requirements.txt


